import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import PriceMarquee from "@/components/PriceMarquee";
import { Suspense } from "react";
import GlobalSuspense from "@/components/GlobalSuspense";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GlobalSuspense>
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{ duration: 3000 }}
          />
          <Navbar></Navbar>
          <PriceMarquee />
          <main className="container mx-auto">{children}</main>
        </GlobalSuspense>
      </body>
    </html>
  );
}
